name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install and setup ngrok for SSH
      uses: tmshkr/ngrok-ssh@latest
      with:
        NGROK_AUTHTOKEN: ${{ secrets.NGROK_AUTHTOKEN }}
        NGROK_CONFIG_FILE: "ngrok.yml"
        WAIT_FOR_CONNECTION: true  # Ждет подключения к туннелю перед продолжением

    - name: Install SSH key
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v3
      with:
        context: .
        push: true
        tags: ${{ secrets.IMAGE_NAME }}

    - name: Deploy to Kubernetes
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.K8S_HOST }}
        username: arman  # Указание имени пользователя для SSH
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: ${{ secrets.K8S_PORT }}
        script: |
          kubectl apply -f ./k8s/deployment.yaml
          kubectl apply -f ./k8s/service.yaml
          kubectl apply -f ./k8s/ingress.yaml
          kubectl apply -f ./k8s/pod.yaml
          kubectl apply -f ./k8s/postgresql-service.yaml
          kubectl apply -f ./k8s/postgresql-statefulset.yaml

    - name: Start application
      run: npm start

    - name: Long-running process
      run: sleep 3600  # Оставляем workflow активным на час
